name: URL Checks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  load_json:
    name: Load URLs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataFile:
          - { "path": "src/data/links.json", "property": "linkData" }
          - { "path": "src/data/projects.json", "property": "projects" }
    outputs:
      urls: ${{ steps.set_output.outputs.urls }}
    steps:
      - uses: actions/checkout@v4
      - name: Get specified property
        id: load_urls
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{ matrix.dataFile.path }}
          prop_path: ${{ matrix.dataFile.property }}
      - name: Set output
        id: set_output
        run: echo "::set-output name=urls::${{ toJSON(steps.load_urls.outputs.value) }}"

  check:
    name: Check URLs
    runs-on: ubuntu-latest
    needs: load_json
    strategy:
      matrix:
        url: ${{ fromJson(needs.load_json.outputs.urls) }}
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: ${{ matrix.url }}
          follow-redirect: true
