name: URL Checks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  load_json:
    name: Load URLs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataFile:
          - { "path": "src/data/links.json", "property": "linkData" }
          - { "path": "src/data/projects.json", "property": "projects" }
    outputs:
      matrix: ${{ steps.json.outputs.linkData }}
    steps:
      - uses: actions/checkout@v4
      - name: get specified property
        id: load_urls
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ${{matrix.dataFile.path}}
          prop_path: ${{matrix.dataFile.property}}
      - run: |
          echo steps.load_urls.outputs
      - id: json
        run: |
          echo "linkData=${{ toJSON(steps.load_urls.outputs.value) }}" >> $GITHUB_OUTPUT

  get_urls:
    name: Get URLs
    runs-on: ubuntu-latest
    needs: [load_json]
    strategy:
      matrix:
        value: ${{ fromJson(needs.load_json.outputs.matrix) }}
    outputs:
      matrix: ${{ steps.get_url.outputs.urls }}
    steps:
      - run: |
          echo ${{ toJSON(matrix.value) }}
      - id: get_url
        run: |
          echo "urls=${{ toJSON(matrix.value) }}" >> $GITHUB_OUTPUT

  check:
    name: Check URLs
    runs-on: ubuntu-latest
    needs: [get_urls]
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_urls.outputs.matrix) }}
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: ${{matrix.value.url}}
          follow-redirect: true
